Add log
aicers/review-web pull request #27
Opened 2023-05-22 05:43 UTC by dayeon5470

Fixes #22

2023-05-22 17:49 UTC, msk commented
#22 에는 로그인 실패도 로그를 남기도록 되어 있는데, 이 PR에는 성공한 경우만 있는 것 같은데요.

2023-05-23 16:09 UTC, msk requested changes

2023-05-25 12:07 UTC, sehkone commented on src/graphql/account.rs
> +            info!("invalid {username}");
`info!("{username} is invalid")`가 더 명확

2023-05-25 12:11 UTC, sehkone commented on src/graphql/account.rs
> +            Err("incorrect username".into())
`info!`와 같은 메시지를 적도록 합시다.

2023-05-25 16:26 UTC, msk commented on src/graphql/account.rs
> +            Err("incorrect username".into())
GraphQL API의 리턴값과 로그 메시지는 읽는 주체가 다릅니다. 전자는 웹으로 API를 호출하는 사용자이고 후자는 서버 관리자입니다. 서버 관리자에게는 되도록 상세한 정보를 제공하는 것이 맞지만, 사용자는 계정과 암호 정보를 알아내려고 무작위로 대입하는 공격자일 수도 있기 때문에 "incorrect username or password"처럼 모호한 메시지를 주는 것이 맞습니다. 어떤 것이 틀렸는지 알려주는 것만으로 공격자가 시도해야할 가지수를 대폭 줄여주게 됩니다.

2023-05-27 00:41 UTC, sehkone commented on src/graphql/account.rs
> +            Err("incorrect username".into())
@dayeon5470 , @msk 의 지적이 맞습니다. `info!`와 같은 메시지로 적지 말고 원래 코드로 되돌려 주세요. 두 분에게 혼선을 빚게 한 점은 양해 바래요~

2023-05-30 16:46 UTC, msk approved these changes

2023-05-30 16:46 UTC, merged