Added `eventstream` Graphql API to fetch events periodically
aicers/review-web pull request #35
Opened 2023-05-30 04:20 UTC by kimhanbeom

Closes: #7

2023-05-30 09:47 UTC, syncpark requested changes

2023-05-30 09:47 UTC, syncpark commented on src/graphql/event.rs
> +const EVENT_FETCH_TIME: u64 = 60 * 30;
Please set the default `EVENT_FETCH_TIME` value to 20 seconds and consider to read this value from the config.toml

2023-05-30 09:47 UTC, syncpark commented on src/graphql/event.rs
> +    let mut dsn_covert_time = start_time;
dsn -> dns?

2023-05-30 09:47 UTC, syncpark commented on src/graphql/event.rs
> +    let mut repeate_http_time = start_time;
repeate -> repeat?

2023-05-30 16:35 UTC, msk approved these changes

2023-05-31 01:16 UTC, syncpark approved these changes

2023-05-31 01:16 UTC, merged