Added graphql api for trusted user agent
aicers/review-web pull request #48
Opened 2023-06-16 00:58 UTC by kimhanbeom

- Add the ability to list/insert/remove/update/apply graphql api for `trusted user agent`.

reference: https://github.com/aicers/hog/issues/414

2023-06-16 05:04 UTC, syncpark requested changes

2023-06-16 05:09 UTC, msk commented on src/graphql/trusted_user_agent.rs
> +            String::from_utf8(key.to_vec()).context("invalid user-agent in database")?;
`key`값은 RocksDB가 파일에서 읽어오는 거라서 파일시스템 오류 등으로 데이터베이스에서 잘못된 값이 읽히는 경우를 대비해야 하지 않을까요?

2023-06-16 05:17 UTC, syncpark commented on src/graphql/trusted_user_agent.rs
> +            String::from_utf8(key.to_vec()).context("invalid user-agent in database")?;
위의 경우에서 DB 혹은 파일시스템 문제보다는 User agent 문자열에 UTF8 변환이 안되는 바이너리 값이 섞여들어가서 변환이 안되는 상황이라고 봤습니다.

이런 경우 DB에도, 파일시스템에도 아무런 문제가 없지만 데이터를 읽지 못하는 상황이 반복되지 않을까요? DB에 저장되어있지만 사용할 수 없는 데이터가 될겁니다.

그러니 처음 데이터를 입력할 때 UTF8 변환이 안되는 데이터는 거르거나, 그게 아니라 이미 DB에 들어가 있다면 최대한 사용할 수 있어야하지 않을까요?

2023-06-16 05:27 UTC, msk commented on src/graphql/trusted_user_agent.rs
> +            String::from_utf8(key.to_vec()).context("invalid user-agent in database")?;
이미 DB에 들어가 있는 값을 신뢰할 수 있느냐 하는 건 결국 어느 정도까지의 무결성을 가정할 건지의 문제인데요, 저희 쪽에서는 CPU와 메모리에는 오류가 없는 것으로, 그 외의 경우(디스크, 네트워크 등)는 오류가 생길 수 있는 것으로 가정하고 에러 처리도 그에 맞춰서 하고 있습니다. REview 실행 환경상 RocksDB가 읽는 파일에는 문제가 없거나, 문제가 생길 때 panic이 나도 괜찮다라고 가정하면 expect를 쓰는 게 맞겠네요. 그 가정을 하게 되면 RocksDB에서 읽은 값의 deserialization 에러도 처리할 필요가 없어서 코드가 상당히 간결해집니다.

2023-06-20 00:25 UTC, syncpark approved these changes

2023-06-20 00:29 UTC, merged