Add BlockList events
aicers/review-web pull request #59
Opened 2023-08-02 08:42 UTC by dayeon5470

https://github.com/petabi/review-database/issues/118

2023-08-04 04:24 UTC, syncpark requested changes

2023-08-04 04:24 UTC, syncpark commented on Cargo.toml
> +review-database = { git = "https://github.com/dayeon5470/review-database.git", branch = "block_list" }
review-database를 먼저 릴리즈한 후 그 버전으로 수정해서 올려주세요.

2023-08-14 09:29 UTC, syncpark requested changes

2023-08-14 09:29 UTC, syncpark commented on src/graphql/event.rs
> +struct BlockListType {
이걸 struct이 아닌 ENUM으로 처리할 수는 없을까요? 한 번 검토해보세요

2023-08-16 01:24 UTC, dayeon5470 commented on src/graphql/event.rs
> +struct BlockListType {
enum으로 하면 #[derive(Union)] 에서 오류나서 struct로 했어요

2023-08-16 01:59 UTC, syncpark commented on src/graphql/event.rs
> +struct BlockListType {
그럼 아예 BlockList 이벤트를 프로토콜 단위로 분리하면 어떨까요?
`BlockList(BlockListType)` 처럼 하나로 묶지 말고 `BlockListConn<BlockListConn>` 처럼요.

2023-08-17 05:00 UTC, syncpark approved these changes

2023-08-22 01:42 UTC, merged